Removed deprecation warnings
ros-perception/image_pipeline pull request #1010
Opened 2024-06-26 08:50 UTC by ahcorde

Removed deprecation warnings included recently in message_filters

2024-07-11 12:27 UTC, clalancette requested changes

2024-07-11 12:27 UTC, clalancette commented on depth_image_proc/src/disparity.cpp
> +          rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(rmw_qos_profile_default)));
I think we can simplify this to:

```suggestion
        sub_info_.subscribe(this, "right/camera_info", rclcpp::QoS(10));
```

(same goes for all of the other instances below)

2024-07-11 12:27 UTC, clalancette commented on image_view/include/image_view/disparity_view_node.hpp
> +  explicit DisparityViewNode(DisparityViewNode &&) = delete;
Hm, this is changing the node from being copyable to not being copyable.  Can you explain more about why we should do this?

2024-07-12 11:10 UTC, ahcorde commented on image_view/include/image_view/disparity_view_node.hpp
> +  explicit DisparityViewNode(DisparityViewNode &&) = delete;
removed, I was testing something

2024-07-12 12:27 UTC, clalancette requested changes

2024-07-12 12:27 UTC, clalancette commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +          rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(sensor_data_qos)), sub_opts);
I think we should refactor this a bit.

Above on line 318, we can change sensor_data_qos to:

```
const SensorDataQoS sensor_data_qos;
```

Then in line 327-328, we can change the code to use `get_rmw_qos_profile`:

```
        sub_l_image_.subscribe(
          this, left_topic, hints.getTransport(), sensor_data_qos.get_rmw_qos_profile(), sub_opts);
```

And then finally, on this line, we can do:

```suggestion
        sub_l_info_.subscribe(this, left_info_topic, sensor_data_qos, sub_opts);
```

I think that is a lot more readable than using the `QoSInitialization::from_rmw` method.

2024-07-12 12:27 UTC, clalancette commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +          rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(sensor_data_qos)), sub_opts);
Same here.

2024-07-12 12:27 UTC, clalancette commented on stereo_image_proc/src/stereo_image_proc/point_cloud_node.cpp
> +          rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(sensor_data_qos)), sub_opts);
And the same basic idea here.

2024-07-23 10:30 UTC, clalancette approved these changes

2024-07-23 10:38 UTC, merged