launch image view with a predefined window size
ros-perception/image_pipeline pull request #218
Opened 2016-08-10 15:35 UTC by wiseware-ros

We came across a use case where we want to launch an image_view window with a predefined window size. The solution checks if autoscale is not set and introduces two new ROS parameters (width and height). If both are present the window is resized. This way, previous functionality is maintained and the window is only resized if you specifically tell the node to at launch time.

2016-08-23 04:34 UTC, wkentaro commented on image_view/src/nodes/image_view.cpp
> +
It should be 2 space?

2016-10-02 14:46 UTC, vrabaud requested changes

2016-10-02 14:46 UTC, vrabaud commented on image_view/src/nodes/image_view.cpp
> +
yes, please don't use tabs but spaces.

2017-01-02 14:00 UTC, vrabaud commented
Please update to spaces.

2017-04-30 16:43 UTC, closed without merging