enable to set camera_info_url from rosparam, enable to publish depth image
ros-perception/image_pipeline pull request #223
Opened 2016-09-28 17:03 UTC by k-okada

@wkentaro , I think this PR enables what you want to do in https://github.com/ros-perception/image_common/pull/54#issuecomment-248081140

2016-10-01 17:48 UTC, wkentaro commented
This would be a nice feature, but there is still needs to publish pcd and camera_info with synchronization,
which should be added to `pcd_to_pointcloud` as a feature.
Also, in some situation I prefer image and points are synchronized, in that case something like a virtual_camera is required.

2016-10-01 17:51 UTC, wkentaro commented
Also, we need saving node for camera_info, image, depth_image and pcd with synchronization, and we need to create a node to handle all of them.
I'm planning to place that node in `virtual_camera` package, and I think it helps users (including me) to find and use the node in the same package.

2016-10-02 15:32 UTC, vrabaud commented
lgtm. @wkentaro, can I merge ?

2016-10-02 17:46 UTC, wkentaro requested changes

2016-10-02 17:46 UTC, wkentaro commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +        nh_.param("camera_info_url", camera_info_url_);
Why duplication of `nh_.param("camera_info_url", camera_info_url_);`?

2016-10-02 17:46 UTC, wkentaro commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +    std::string camera_info_url_;
Why do you add `_` suffix to variable that is not the data field of the class?

2016-10-27 08:48 UTC, k-okada commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +    std::string camera_info_url_;
removed

2016-10-27 08:48 UTC, k-okada commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +        nh_.param("camera_info_url", camera_info_url_);
that't mistake, removed

2016-10-27 11:03 UTC, wkentaro commented
LGTM

2016-11-06 17:14 UTC, vrabaud commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +          encoding = sensor_msgs::image_encodings::BGRA16; break;
should be BGRA8

2016-11-06 17:14 UTC, vrabaud commented on image_publisher/src/nodelet/image_publisher_nodelet.cpp
> +      std::string encoding = "bgr8";
instead of "bgr8", it should be sensor_msgs::image_encodings::BGR8 (yes, it was wrong before).

2016-11-06 17:16 UTC, vrabaud commented
BTW, the title of this PR is "enable to publish depth image", I guess you mean "enable to publish images of depth other than bgr8", right ?

2017-01-02 14:00 UTC, vrabaud commented
Please address the latest fixes.

2017-03-08 01:50 UTC, k-okada commented
@vrabaud I'm very sorry for super late response, fixed the code.

2019-04-22 13:42 UTC, JWhitleyAStuff commented
@k-okada - Is this still a problem and, if so, could you rebase on Melodic?

2019-06-12 21:30 UTC, JWhitleyAStuff commented
Closing based on lack of response.

2019-06-12 21:30 UTC, closed without merging