Modified the implementation of video_recorder to mantain frame rate output
ros-perception/image_pipeline pull request #237
Opened 2016-11-28 06:42 UTC by zenified

modified video_recorder to maintain framerate when video stream experience frame drops

2016-12-04 22:02 UTC, vrabaud requested changes
this change is way to complex for what it's supposed to do, please simplify (mostyl, reduce the number of skipped line and remove all the code you probably used for debugging).
The overall goal is good though so tthx, it's doing it the proper way !

2016-12-04 22:02 UTC, vrabaud commented on image_view/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS}")
we can't ask for a package to depend on C++11 during a release cycle. Please remove this line and have your code use proper C++03 code. Thx

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +    // ROS_INFO_STREAM("last rec:  " << (image_msg->header.stamp - g_last_wrote_time) <<" min time: "<<ros::Duration(1.0 / fps));
remove this comment.

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +
too many skipped lines, please remove

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +
why has const disappeared ?

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +      captured++;
that variable is useless.

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +        }
} else {

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +ros::NodeHandle* _nh;
what is that variable for ?

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +          g_last_wrote_time = ros::Time::now();
g_last_wrote_time is now useless as it is write-only no ?

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +            imageBuff = cv_bridge::cvtColorForDisplay(cv_bridge::toCvShare(image_msg), encoding, options)->image.clone();
why not imageCapture.clone() ?

2016-12-04 22:02 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +int called = 0;
useless variable

2016-12-27 07:15 UTC, zenified commented
Thanks for the feedback, apology for not cleaning up the code properly before the merge request.

2017-01-02 12:42 UTC, vrabaud requested changes
Please use a C++ formatter and maybe a GUI to show which variables are useless.

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +    int numRun = 10;
useless variable

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +    float duration =60;
useless variable

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +    float totalTime = 0;
useless variable

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +
don't skip line

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +
too many

skipped

lines

below

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +          for( int x = 0; x<imagePad;x++)
use a formatter to give something proper with spaces like: for(int x=0; x<imagePad; ++x)

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +        }
please address

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +    std::cout << "\nVideo saved to " <<filename<<  std::endl;
please respect spaces.

2017-01-02 12:42 UTC, vrabaud commented on image_view/src/nodes/video_recorder.cpp
> +            imageBuff = cv_bridge::cvtColorForDisplay(cv_bridge::toCvShare(image_msg), encoding, options)->image.clone();
please address

2017-01-03 04:21 UTC, zenified commented
I have formatted the code with clang-format as recommended in the ros style guide. The formatting issues should have all been corrected.

I have ran the code the code through a static analyzer and removed all the redundant variables  identified.

Thanks again and apologies for trouble

2017-01-03 08:22 UTC, vrabaud commented
aaaaaaah, you should never run a formatter on the whole file, only on the section you modified :) Otherwise it makes things very hard for me to review (look at the diff size, it's crazy now). Any way you can revert your previous commit? (in Eclipse, you can only format a section, not sure about other editors).

2017-01-03 09:04 UTC, zenified commented
ah my bad.. let me try to revert ><

2017-01-03 09:31 UTC, zenified commented
If this revert makes the changes too messy, perhaps i could close this pull request and try to rebase properly on my end before I raise another request.

2019-04-22 13:45 UTC, JWhitleyAStuff commented
@zenified - If this is still needed, please re-apply these changes in a new, cleaner PR against Melodic.

2019-04-22 13:45 UTC, closed without merging