Add trigger srv to recorder
ros-perception/image_pipeline pull request #493
Opened 2020-01-09 14:29 UTC by ipa-lth

I added service to start and stop the recording.
Further a parameter "save_all_video" (compare: image_saver) has to be set to false to enable the services.

The atomic bool requires c++11.

2020-08-19 14:44 UTC, JWhitleyWork requested changes

2020-08-19 14:44 UTC, JWhitleyWork commented on image_view/src/nodes/video_recorder.cpp
> +            ROS_INFO_STREAM("Recording frame " << g_count << "\x1b[1F");
Can you please make this `ROS_DEBUG`? There's no need to spam the terminal every frame.

2020-08-19 14:44 UTC, JWhitleyWork commented on image_view/src/nodes/video_recorder.cpp
> +              ROS_WARN("Frame skipped, no data!");
This can be `ROS_WARN_ONCE` or `ROS_WARN_THROTTLE` to avoid spamming.

2020-08-19 14:44 UTC, JWhitleyWork commented on image_view/src/nodes/video_recorder.cpp
> +    ROS_INFO("STARTING");
Prefer "Starting recording" (more context is better).

2020-08-19 14:44 UTC, JWhitleyWork commented on image_view/src/nodes/video_recorder.cpp
> +    ROS_INFO("Stoping");
Same - "Stopping recording" (also spelling).

2020-08-19 14:46 UTC, JWhitleyWork commented
Just a few questions:

1. Why target this at `kinetic` instead of `melodic` or `noetic`? It's much preferred to target newer releases and then back-port if necessary.
2. Has this been tested with real hardware?

2020-09-23 07:47 UTC, ipa-lth commented
I tested it with real hardware (but on kinetic). I have no doubt about melodic/noetic, but I probably cannot test it on real hardware. I will see what I can do

2022-12-04 22:15 UTC, JWhitleyWork commented
Very late ping to @ipa-lth for testing / re-targeting to `melodic` or `noetic`.

2024-01-19 00:51 UTC, mikeferguson commented
No response in over a year, and targeting a very dead branch

2024-01-19 00:51 UTC, closed without merging