fixes for fisheye calibration
ros-perception/image_pipeline pull request #542
Opened 2020-06-10 12:44 UTC by soeroesg

fix #503:
set_cammodel of StereoCalibrator need to override the method of parent class

fix related to https://github.com/opencv/opencv/issues/11085

unlike cv2.calibrate, the cv2.fisheye.calibrate method expects float64 points and in an array with an extra dimension. The same for cv2.stereoCalibrate vs cv2.fisheye.stereoCalibrate

2020-06-10 18:53 UTC, SteveMacenski approved these changes
@JWhitleyWork any issues?

2020-06-10 18:53 UTC, SteveMacenski commented
@soeroesg please submit this patch to `noetic` and `ros2` before we merge this to keep them synced

2020-06-10 20:18 UTC, JWhitleyWork requested changes

2020-06-10 20:18 UTC, JWhitleyWork commented on camera_calibration/src/camera_calibration/calibrator.py
> +        #print("cam model set: " + str(self.camera_model))
Please remove this debugging print that is commented out. Leaving in commented-out code is bad practice.

2020-06-10 20:19 UTC, JWhitleyWork commented
Just one minor thing.

2020-06-12 10:03 UTC, soeroesg commented on camera_calibration/src/camera_calibration/calibrator.py
> +        #print("cam model set: " + str(self.camera_model))
I removed that commented line and I pushed all changes to noetic too.

indigo, kinetic, ros2 have no fisheye camera at all. Do you want me to add the complete fisheye calibration to ros2? I pushed the whitespace trimming to these branches too.

@SteveMacenski

2020-06-12 17:56 UTC, SteveMacenski commented on camera_calibration/src/camera_calibration/calibrator.py
> +        #print("cam model set: " + str(self.camera_model))
@soeroesg adding it to ROS2 would be really appreciated if you had the time, yes.

2020-06-12 18:38 UTC, JWhitleyWork approved these changes

2020-06-12 18:38 UTC, merged

2020-06-12 18:42 UTC, SJamieson commented
Thanks @soeroesg and @JWhitleyWork!

2020-06-13 07:37 UTC, soeroesg commented on camera_calibration/src/camera_calibration/calibrator.py
> +        #print("cam model set: " + str(self.camera_model))
I pushed the implementation to the ros2 branch too, but I have no ROS2 to test, so please test it