Make GTK3 and harfbuzz optional
ros-perception/image_pipeline pull request #601
Opened 2020-09-19 07:22 UTC by seanyen

Those dependency is not mandatory and the `image_view` is already resilient enough when those packages are absent.

This pull request is to make them optional.

(This is motivated while we enabled it for ROS on Windows project.)

2020-10-08 18:57 UTC, JWhitleyWork requested changes
On what systems/environments have you tested this change? Are you sure that all modules in `image_view` will run without these dependencies?

2020-10-08 18:57 UTC, JWhitleyWork commented on image_view/CMakeLists.txt
>  include_directories(${GTK3_INCLUDE_DIRS})
I recommend the following:

```suggestion
pkg_check_modules(GTK3 gtk+-3.0)
if(GTK3_FOUND)
  include_directories(${GTK3_INCLUDE_DIRS})
else()
  message(STATUS "GTK3 is not found. Some features are disabled.")
endif()
```

2020-10-08 18:57 UTC, JWhitleyWork commented on image_view/CMakeLists.txt
>  include_directories(${PC_HB_INCLUDE_DIRS})
Same here:

```suggestion
pkg_check_modules(PC_HB harfbuzz)
if(PC_HB_FOUND)
  include_directories(${PC_HB_INCLUDE_DIRS})
else()
  message(STATUS "harfbuzz is not found. Some features are disabled.")
endif()
```

2020-10-08 19:30 UTC, seanyen commented
> On what systems/environments have you tested this change? Are you sure that all modules in image_view will run without these dependencies?

On Windows! We natively run the [ROS on Windows](https://discourse.ros.org/t/ros-on-windows-melodic-release-v20200915-0-0-2009211616). My test coverage might not be 100%, but the `image_view` gets the image feed and it seems to be functional by this configuration. Let me know if any use cases I need to pay attention to.

![test](https://user-images.githubusercontent.com/25241284/95504661-f44b8600-0961-11eb-8743-4ef7779afa9e.png)

2020-12-11 23:58 UTC, JWhitleyWork commented
@seanyen Sorry I haven't been back around to this for a while. Would you mind rebasing on the upstream `noetic` so I can test?

2020-12-12 00:00 UTC, JWhitleyWork commented
Additionally, I would prefer to remove the GTK dependency completely and just let OpenCV deal with it. Would you mind implementing that in this PR?

2021-01-25 22:47 UTC, JWhitleyWork commented
@seanyen Ping for updates.

2021-01-29 21:23 UTC, seanyen commented
@JWhitleyWork
Sorry for being late on this. Just got back from my parental leave. 👶🍼

I rebased to the latest noetic, removed the harfbuzz dep (which seems to be extra), and removed GTK3 dep as you suggested.

2021-05-03 17:55 UTC, JWhitleyWork approved these changes

2021-05-03 17:55 UTC, JWhitleyWork commented
Sorry for the very late reply. Merged!

2021-05-03 17:55 UTC, merged