Add QoS overrides
ros-perception/image_pipeline pull request #651
Opened 2021-04-14 23:01 UTC by audrow

2021-04-14 23:29 UTC, jacobperron commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +    rclcpp::QosPolicyKind::Invalid,
I think we should remove `rclcpp::QosPolicyKind::Invalid`; I guess it will result in a runtime exception.

2021-04-14 23:29 UTC, jacobperron commented on stereo_image_proc/src/stereo_image_proc/point_cloud_node.cpp
> +    rclcpp::QosPolicyKind::Invalid,
Same here

2021-05-19 17:54 UTC, jacobperron approved these changes
LGTM, one nitpick

2021-05-19 17:54 UTC, jacobperron commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +    sub_opts);
nit: I think we can use up to 100 characters per line. I think we can format this and similar lines in this PR, e.g.
```suggestion
    this, "left/image_rect", hints.getTransport(), image_sub_rmw_qos, sub_opts);
```

2021-05-19 17:59 UTC, jacobperron commented
We should make sure the CI jobs are green before merging. Since this change is not compatible with Foxy, we should probably branch (FYI @JWhitleyWork). For Rolling, we should make releases for the changes to image_common and message_filters (I can help with that); for Galactic it may require backporting those changes (I'll check when releasing for Rolling).

2021-05-19 20:08 UTC, audrow commented
I think I'm going to make a PR to `rclcpp` to create a default QoS override options object to remove some redundancy.

2021-05-19 20:35 UTC, jacobperron requested changes

2021-05-19 20:35 UTC, jacobperron commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +    rclcpp::QosPolicyKind::Liveliness,
In retrospect, I don't think that it makes sense to make liveliness configurable. If the someone changes this to MANUAL_BY_TOPIC, there's nothing in this code to trigger the manual heartbeat.

2021-05-19 21:50 UTC, jacobperron commented on stereo_image_proc/src/stereo_image_proc/disparity_node.cpp
> +    rclcpp::QosPolicyKind::Liveliness,
Following our offline conversation, let's just use the default policies defined here to keep it simple: https://github.com/ros2/rclcpp/blob/0251f70fe8a952fae242e6dcdc5b11bc4c11dc76/rclcpp/include/rclcpp/qos_overriding_options.hpp#L141

2021-05-19 22:45 UTC, jacobperron approved these changes

2021-05-25 16:43 UTC, jacobperron commented
@JWhitleyWork Friendly ping for review. It sounds like we may also want to re-target this to a new `rolling` branch once it exists (https://github.com/ros-perception/image_pipeline/pull/659#issuecomment-846670771)

2021-06-02 20:37 UTC, jacobperron commented
@ros-pull-request-builder retest this please

2021-06-22 20:19 UTC, pmusau17 commented
Tested this on ros2 galactic and ros2 rolling. It builds and passes all tests. I made two small edits to the package.xml files in this [PR](https://github.com/audrow/image_pipeline/pull/1).

2021-06-28 23:29 UTC, jacobperron commented
Re-targeted `rolling`.

2021-07-07 20:49 UTC, clalancette commented
@ros-pull-request-builder retest this please

2021-07-08 14:40 UTC, clalancette commented
@ros-pull-request-builder retest this please

2021-07-22 23:21 UTC, JWhitleyWork approved these changes

2021-07-22 23:21 UTC, merged