migrate and update image_proc docs
ros-perception/image_pipeline pull request #925
Opened 2024-02-04 01:48 UTC by mikeferguson

* move component documentation from ros wiki, update for various changes
 * add tutorial on how to run components
 * update tutorial on debayer/rectify to use launch file
 * remove image_proc node, it has always been completely broken and the launch file has the same (but working) functionality
 * update launch file to support namespace parameter for tutorial

2024-02-04 01:48 UTC, mikeferguson commented
Testing done:
 * builds locally with rosdoc2
 * launch file tutorial is fully tested

2024-02-05 08:59 UTC, ahcorde requested changes
same small comments and maybe add in the `README.md` the command to build the documentation ?

2024-02-05 08:59 UTC, ahcorde commented on image_proc/doc/conf.py
> +# Copyright 2019 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2024 Open Source Robotics Foundation, Inc.
```

2024-02-05 08:59 UTC, ahcorde commented on image_proc/doc/tutorials.rst
> +```
```suggestion
```bash
```

2024-02-05 08:59 UTC, ahcorde commented on image_proc/doc/tutorials.rst
> +ros2 topic list | grep image_raw
```suggestion
$ ros2 topic list | grep image_raw
```

2024-02-05 08:59 UTC, ahcorde commented on image_proc/doc/tutorials.rst
> +```
```suggestion
```bash
```

2024-02-05 08:59 UTC, ahcorde commented on image_proc/doc/tutorials.rst
> +```
```suggestion
```bash
```

2024-02-05 13:27 UTC, mikeferguson commented
All great suggestions - but I'm going to skip adding build instructions to the README since we aren't doing anything fancy - just using rosdoc2 in the standard way

2024-02-05 13:37 UTC, merged