Humble: Fix loading of the camera info parameters on startup
ros-perception/image_pipeline pull request #983
Opened 2024-05-25 13:03 UTC by Kotochleb

As described in https://github.com/ros-perception/image_pipeline/issues/965 camera info is not loaded from the file on node initialization, but only when the parameter is reloaded.

This PR resolves this issue and should be straightforward to port it to `Iron`, `Jazzy` and `Rolling`.

2024-05-27 08:15 UTC, ahcorde reviewed
can you target `rolling` ? then I will backport this to the other distros

2024-05-27 10:49 UTC, Kotochleb commented
@ahcorde the changes were retargeted to `rolling` as requested.

2024-05-27 11:30 UTC, ahcorde requested changes

2024-05-27 11:30 UTC, ahcorde commented on image_publisher/src/image_publisher.cpp
> +      RCLCPP_INFO(get_logger(), "param_change_callback");
remove

2024-05-27 11:30 UTC, ahcorde commented on image_publisher/src/image_publisher.cpp
> -  timer_ = this->create_wall_timer(
if you remove these lines the `dowork` method will never be called and the image will be never flipped

2024-05-27 12:05 UTC, Kotochleb commented on image_publisher/src/image_publisher.cpp
> +      RCLCPP_INFO(get_logger(), "param_change_callback");
Done

2024-05-27 12:10 UTC, Kotochleb commented on image_publisher/src/image_publisher.cpp
> -  timer_ = this->create_wall_timer(
The timer is set in the `reconfigureCallback`. I didn't want to repeat the `CameraInfoManager` block of code in `onInit` and did not want to create timer there just to recreate it once again in `reconfigureCallback`.

2024-05-28 09:34 UTC, Kotochleb commented
@ahcorde FYI changes from https://github.com/ros-perception/image_pipeline/pull/985 are already merged in here.

2024-05-29 16:04 UTC, ahcorde approved these changes

2024-05-29 16:04 UTC, merged

2024-05-29 16:05 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy humble iron