Humble: Add field of view parameter
ros-perception/image_pipeline pull request #985
Opened 2024-05-26 13:47 UTC by Kotochleb

Currently, the default value for focal length when no camera info is provided defaults to `1.0` rendering whole approximate intrinsics and projection matrices useless.  Based on [this article](https://learnopencv.com/approximate-focal-length-for-webcams-and-cell-phone-cameras/), I propose a better approximation of the focal length based on the field of view of the camera. 

For most of the use cases, users will either know the field of view of the camera the used, or they already calibrated it ahead of time.

If there is some documentation to fill. please let me know.

This PR should be straightforward to port it to `Iron`, `Jazzy` and `Rolling`.

2024-05-27 08:14 UTC, ahcorde requested changes
Do you mind to target `rolling` ? then we can backport this to the other distros.

2024-05-27 08:14 UTC, ahcorde commented on image_publisher/src/image_publisher.cpp
> +  double f_approx = (camera_info_.width / 2) / tan((field_of_view_ * M_PI / 180) / 2);
```suggestion
  double f_approx = (camera_info_.width / 2) / std::tan((field_of_view_ * M_PI / 180) / 2);
```

2024-05-27 10:48 UTC, Kotochleb commented
@ahcorde the changes were retargeted to `rolling` as requested, plus I added documentation for the new parameter since this branch accounts for that.

2024-05-27 10:49 UTC, Kotochleb commented
@ahcorde the changes were retargeted to `rolling` as requested.

2024-05-27 13:47 UTC, ahcorde requested changes

2024-05-27 13:47 UTC, ahcorde commented on image_publisher/src/image_publisher.cpp
> +  double f_approx = (camera_info_.width / 2) / std::tan((field_of_view_ * M_PI / 180) / 2);
is the default value `50` returning `1` ? as the current behavior ?

2024-05-27 21:11 UTC, Kotochleb commented on image_publisher/src/image_publisher.cpp
> +  double f_approx = (camera_info_.width / 2) / std::tan((field_of_view_ * M_PI / 180) / 2);
It doesn't, and I forgot to account for breaking changes. I changed it now so when FOV is 0 or less, it disables the whole feature and uses 1.0 for focal length instead. The default vale is now zero as well, so now the whole thing is not breaking anything.

2024-05-28 09:24 UTC, ahcorde approved these changes

2024-05-28 09:24 UTC, merged

2024-05-28 09:25 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy humble iron